const BusinessCategories = [
  "All categories",
  "Accommodation",
  "Accounting",
  "Acupuncture",
  "Advertising Agencies",
  "Agricultural Services",
  "Air Conditioning / Refrigeration",
  "Alternative Healthcare and Treatments",
  "Animals & Pets",
  "Antiques",
  "Archaeologists",
  "Architectural Services",
  "Arts and Crafts",
  "Assessors and Adjusters",
  "Auctioneers and Property Management",
  "Automotive",
  "Aviation",
  "Bar and Restaurants",
  "Beauty Salons and Salon Supplies",
  "Boilers Servicing and Repairs",
  "Book Publishers and Printers",
  "Bookshops",
  "Breads and Cakes",
  "Building and Construction",
  "Business Services",
  "Chemicals",
  "Childcare and Children",
  "Chiropodists",
  "Chiropractors",
  "Cleaning and Hygiene",
  "Clinics and Treatments",
  "Community and Social",
  "Computers and Internet",
  "Consultancy",
  "Consumer Goods",
  "Convalescent Homes",
  "Corporate Entertainment and Music Supplies and Hospitality",
  "Counselling",
  "Couriers and Freight Forwarding",
  "Craft Centres and Shops",
  "Creches",
  "Data Services",
  "Delicatessens",
  "Dentists and Dental Equipment",
  "Development Agencies",
  "Digital Cameras and Camcorders",
  "Digital Services",
  "Doctors",
  "Doors and Windows",
  "Drain and Sewer Cleaning and Hygiene",
  "Dressmakers",
  "Drinks Distributor",
  "Driving Instructors",
  "Dry Cleaners and Laundries",
  "Education & Colleges",
  "Electrical and Electronics",
  "Engineering",
  "Entertainment and Music Supplies",
  "Film Production Services and Studios",
  "Financial Services",
  "Florists",
  "Food and Drink",
  "Funeral Directors",
  "Furniture and Household",
  "Garden Centres and Nurseries",
  "Gas Companies",
  "Genealogists",
  "Glazing",
  "Golf Courses and Clubs",
  "Graphic Designers",
  "Hairdressing & Barbers",
  "Hardware , Software, ICT",
  "Health & Safety",
  "Healthcare, Medical Services and Supplies",
  "Hire - Repair and Sales",
  "Household - Bedroom and Bathroom",
  "ICT, Hardware , Software",
  "Insulation Contractors",
  "Insurance",
  "Jewellers and Equipment",
  "Landscape Design and Contractors",
  "Libraries",
  "Local Goverment and Authorities",
  "Locksmiths",
  "Machinery and Equipment",
  "Manufacturing",
  "Marine Services, Retail and Online Sales",
  "Marketing Consultancy",
  "Media and Entertainment",
  "Media, Entertainment and Music Supplies",
  "Medical Services and Supplies",
  "Menswear",
  "Miscellaneous - TBC",
  "Mobile Phone and Communications",
  "Mobility Equipment",
  "Off Licence",
  "Off License",
  "Office",
  "Opticans Service and Supplies",
  "Outsourced Business Management",
  "Pharmaceuticals",
  "Pharmacy/Chemists",
  "Photography",
  "Physiotherapists",
  "Printers",
  "Printing",
  "Property and Building Maintenance",
  "Recruitment and Jobs",
  "Recycling",
  "Religious Organisations",
  "Retail and Online Sales",
  "Retail and Online Sales Supplies",
  "Security",
  "Services",
  "Software - ICT",
  "Solar Energy Equipment",
  "Solicitors",
  "Solicitors, Lawyers and Legal Advisors",
  "Sports, Health and Leisure",
  "Stud/Equestrian Centre",
  "Taxis",
  "Tourism",
  "Trade Unions",
  "Training and Education",
  "Transport",
  "Travel Services and Tourism",
  "Vending Sales & Service",
  "Vets",
  "Waste Services",
  "Water Services",
  "Web Design",
  "Wedding Services",
  "Wholesale Supplies",
];

export default BusinessCategories;
